rm *.class
javac Courses.java
javac Instructors.java
javac LectureStack.java
javac Period.java
javac Periods.java
javac Rooms.java
javac SC.java
javac SCIR.java
javac Sections.java
javac Timeslots.java
javac DataManager.java
javac LogicMgr.java
javac ATSManager.java
